name: Pre-release PR
on:
  push:
    branches:
    - release-v1.6.7
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "pre-release, automated pr"
